name: Build and Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Cache node_modules for faster builds
    - name: Cache node_modules
      uses: actions/cache@v3
      id: node-modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-${{ matrix.node-version }}-
    
    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests with coverage
      run: npm test -- --coverage
    
    - name: Upload test coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-node-${{ matrix.node-version }}
        path: coverage/
        retention-days: 7

